name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache dependências Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Executar testes
      run: ./mvnw clean test
      
    - name: Gerar relatório de cobertura
      run: ./mvnw jacoco:report
      
    - name: Upload dos resultados dos testes
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: target/surefire-reports/
        
    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v4
      if: matrix.java-version == '17'  # Só faz upload para uma versão do Java
      with:
        name: coverage-report
        path: target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache dependências Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Compilar aplicação
      run: ./mvnw clean compile
      
    - name: Empacotar aplicação
      run: ./mvnw package -DskipTests
      
    - name: Upload do artefato JAR
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: target/*.jar