name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:  # Permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache dependências Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Executar testes antes do deploy
      run: |
        cd gerenciamento
        ./mvnw clean test
      
    - name: Criar build de produção
      run: |
        cd gerenciamento
        ./mvnw clean package -DskipTests
      
    - name: Upload do artefato para release
      uses: actions/upload-artifact@v4
      with:
        name: production-jar
        path: gerenciamento/target/*.jar
        
    # Adicione aqui steps específicos para seu ambiente de deploy
    # Por exemplo: Docker, AWS, Heroku, etc.
    
    - name: Notificar sucesso do deploy
      run: echo "Deploy realizado com sucesso!"